server:
  port: 9092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: QUESTION-SERVICE
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
